[package]
name = "gitly-git"
authors.workspace = true
edition.workspace = true
version.workspace = true
description.workspace = true

[dependencies]
git2 = "0.20.2"
anyhow.workspace = true
serde.workspace = true
